// Demo data for TriageSetu — 20 curated patient cases + 2 hospitals + beds + staff.
import type { Intake } from "./triage";

export interface DemoPatient extends Intake {
  id: string;
  waitMinutes: number;
  gender?: "male" | "female" | "unknown";
}

// Same as the original Python DEMO list, with gender added for richer UI.
export const DEMO_PATIENTS: DemoPatient[] = [
  {
    id: "TS-101",
    display_name: "Aarav K.",
    age: 4,
    complaint: "High fever, sleepy and refusing fluids",
    heart_rate: 132,
    respiratory_rate: 30,
    spo2: 96,
    temperature: 38.7,
    systolic_bp: 92,
    avpu: "voice",
    history_available: false,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 14,
    gender: "male",
  },
  {
    id: "TS-102",
    display_name: "Ramesh P.",
    age: 68,
    complaint: "Chest tightness and sweating",
    heart_rate: 112,
    respiratory_rate: 23,
    spo2: 94,
    temperature: 37.1,
    systolic_bp: 146,
    avpu: "alert",
    history_available: true,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 21,
    gender: "male",
  },
  {
    id: "TS-103",
    display_name: "Meera S.",
    age: 29,
    complaint: "Twisted ankle while walking",
    heart_rate: 78,
    respiratory_rate: 16,
    spo2: 99,
    temperature: 36.8,
    systolic_bp: 118,
    avpu: "alert",
    history_available: false,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 52,
    gender: "female",
  },
  {
    id: "TS-104",
    display_name: "Unidentified",
    age: 52,
    complaint: "Found unconscious at bus stand",
    heart_rate: 108,
    respiratory_rate: 20,
    spo2: 89,
    temperature: 36.6,
    systolic_bp: 86,
    avpu: "unresponsive",
    history_available: false,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 4,
    gender: "unknown",
  },
  {
    id: "TS-105",
    display_name: "Fatima A.",
    age: 75,
    complaint: "Weakness and new confusion",
    heart_rate: 96,
    respiratory_rate: 22,
    spo2: 95,
    temperature: 37.9,
    systolic_bp: 102,
    avpu: "voice",
    history_available: true,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 33,
    gender: "female",
  },
  {
    id: "TS-106",
    display_name: "Dev R.",
    age: 33,
    complaint: "Deep cut with ongoing bleeding",
    heart_rate: 104,
    respiratory_rate: 19,
    spo2: 97,
    temperature: 36.9,
    systolic_bp: 124,
    avpu: "alert",
    history_available: false,
    active_bleeding: true,
    break_glass: false,
    waitMinutes: 12,
    gender: "male",
  },
  {
    id: "TS-107",
    display_name: "Kavya M.",
    age: 18,
    complaint: "Headache, nausea, light sensitivity",
    heart_rate: 89,
    respiratory_rate: 18,
    spo2: 98,
    temperature: 37.4,
    systolic_bp: 116,
    avpu: "alert",
    history_available: false,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 41,
    gender: "female",
  },
  {
    id: "TS-108",
    display_name: "Sanjay D.",
    age: 46,
    complaint: "Cough, breathing feels harder",
    heart_rate: 106,
    respiratory_rate: 25,
    spo2: 92,
    temperature: 38.2,
    systolic_bp: 130,
    avpu: "alert",
    history_available: false,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 27,
    gender: "male",
  },
  {
    id: "TS-109",
    display_name: "Nila T.",
    age: 2,
    complaint: "Fever and rapid breathing",
    heart_rate: 142,
    respiratory_rate: 36,
    spo2: 94,
    temperature: 39.1,
    systolic_bp: 88,
    avpu: "alert",
    history_available: false,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 9,
    gender: "female",
  },
  {
    id: "TS-110",
    display_name: "Gopal N.",
    age: 71,
    complaint: "Dizzy after missed meals",
    heart_rate: 62,
    respiratory_rate: 15,
    spo2: 97,
    temperature: 36.5,
    systolic_bp: 108,
    avpu: "alert",
    history_available: true,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 63,
    gender: "male",
  },
  {
    id: "TS-111",
    display_name: "Isha V.",
    age: 26,
    complaint: "Mild abdominal discomfort",
    heart_rate: 82,
    respiratory_rate: 17,
    spo2: 99,
    temperature: 37.0,
    systolic_bp: 115,
    avpu: "alert",
    history_available: false,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 48,
    gender: "female",
  },
  {
    id: "TS-112",
    display_name: "Arjun B.",
    age: 39,
    complaint: "Severe abdominal pain, pale",
    heart_rate: 118,
    respiratory_rate: 22,
    spo2: 96,
    temperature: 37.8,
    systolic_bp: 94,
    avpu: "alert",
    history_available: false,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 19,
    gender: "male",
  },
  {
    id: "TS-113",
    display_name: "Leela C.",
    age: 81,
    complaint: "Fall at home; hip pain",
    heart_rate: 90,
    respiratory_rate: 20,
    spo2: 95,
    temperature: 36.8,
    systolic_bp: 138,
    avpu: "alert",
    history_available: true,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 35,
    gender: "female",
  },
  {
    id: "TS-114",
    display_name: "Mohit J.",
    age: 15,
    complaint: "Asthma symptoms, inhaler not helping",
    heart_rate: 124,
    respiratory_rate: 29,
    spo2: 91,
    temperature: 37.2,
    systolic_bp: 106,
    avpu: "alert",
    history_available: true,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 16,
    gender: "male",
  },
  {
    id: "TS-115",
    display_name: "Saira H.",
    age: 31,
    complaint: "Pregnant; bleeding and abdominal pain",
    heart_rate: 102,
    respiratory_rate: 21,
    spo2: 96,
    temperature: 37.0,
    systolic_bp: 110,
    avpu: "alert",
    history_available: true,
    active_bleeding: true,
    break_glass: false,
    waitMinutes: 7,
    gender: "female",
  },
  {
    id: "TS-116",
    display_name: "Vikram L.",
    age: 55,
    complaint: "Medication refill; no acute symptoms",
    heart_rate: 70,
    respiratory_rate: 14,
    spo2: 99,
    temperature: 36.7,
    systolic_bp: 128,
    avpu: "alert",
    history_available: true,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 88,
    gender: "male",
  },
  {
    id: "TS-117",
    display_name: "Rehan Q.",
    age: 7,
    complaint: "Vomiting twice, drinking water",
    heart_rate: 104,
    respiratory_rate: 24,
    spo2: 98,
    temperature: 37.6,
    systolic_bp: 96,
    avpu: "alert",
    history_available: false,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 44,
    gender: "male",
  },
  {
    id: "TS-118",
    display_name: "Anita G.",
    age: 64,
    complaint: "Sudden slurred speech",
    heart_rate: 88,
    respiratory_rate: 18,
    spo2: 97,
    temperature: 36.8,
    systolic_bp: 150,
    avpu: "alert",
    history_available: true,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 23,
    gender: "female",
  },
  {
    id: "TS-119",
    display_name: "Joseph M.",
    age: 49,
    complaint: "Back pain after lifting",
    heart_rate: 80,
    respiratory_rate: 16,
    spo2: 99,
    temperature: 36.6,
    systolic_bp: 121,
    avpu: "alert",
    history_available: false,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 57,
    gender: "male",
  },
  {
    id: "TS-120",
    display_name: "Pooja B.",
    age: 23,
    complaint: "Panic, tingling fingers, fast breathing",
    heart_rate: 112,
    respiratory_rate: 27,
    spo2: 99,
    temperature: 36.9,
    systolic_bp: 120,
    avpu: "alert",
    history_available: false,
    active_bleeding: false,
    break_glass: false,
    waitMinutes: 31,
    gender: "female",
  },
];

export const DEMO_HOSPITALS = [
  {
    code: "DH-MUM-01",
    name: "District Hospital — Mumbai ED",
    type: "urban_trauma",
    bedsTotal: 48,
  },
  {
    code: "RH-PUN-02",
    name: "Rural Health Centre — Pune",
    type: "rural_ed",
    bedsTotal: 22,
  },
];

export function generateBeds(hospitalId: string, total: number) {
  const zones = ["resus", "major", "minor", "observation", "paediatric"];
  const beds: { hospitalId: string; code: string; zone: string; status: string }[] = [];
  const perZone = Math.floor(total / zones.length);
  zones.forEach((zone, zi) => {
    for (let i = 1; i <= perZone; i++) {
      const code = `${zone.slice(0, 3).toUpperCase()}-${String(i).padStart(2, "0")}`;
      // Deterministic occupancy: some occupied, some free
      const seed = (zi * 13 + i * 7) % 10;
      const status = seed < 5 ? "occupied" : seed < 7 ? "cleaning" : seed < 9 ? "reserved" : "free";
      beds.push({ hospitalId, code, zone, status });
    }
  });
  return beds;
}

export const DEMO_STAFF = [
  { name: "N. Patel", role: "triage_nurse", shift: "day", onDuty: true, load: 4 },
  { name: "Dr. R. Iyer", role: "ed_physician", shift: "day", onDuty: true, load: 7 },
  { name: "Dr. S. Khan", role: "consultant", shift: "day", onDuty: true, load: 3 },
  { name: "A. Rao", role: "charge_nurse", shift: "day", onDuty: true, load: 2 },
  { name: "Dr. M. Das", role: "resident", shift: "evening", onDuty: true, load: 5 },
  { name: "P. Nair", role: "triage_nurse", shift: "evening", onDuty: true, load: 3 },
  { name: "Dr. V. Joshi", role: "ed_physician", shift: "night", onDuty: false, load: 0 },
  { name: "K. Mehta", role: "charge_nurse", shift: "night", onDuty: false, load: 0 },
];
