const $=s=>document.querySelector(s);let queue=[],surge=false,filter='all';
const tier=n=>({1:'ESI 1 · Resuscitation',2:'ESI 2 · Emergent',3:'ESI 3 · Urgent',4:'ESI 4 · Less urgent',5:'ESI 5 · Non-urgent'})[n],color=n=>n<=2?'red':n===3?'amber':'green';
const safe=x=>String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function api(path,o={}){let r=await fetch('/api/'+path,o);if(!r.ok)throw Error((await r.json()).detail||'Request failed');return r.json()}
function note(m,bad=false){let x=$('#toast')||Object.assign(document.createElement('div'),{id:'toast'});if(!x.parentNode)document.body.append(x);x.textContent=m;x.className=(bad?'error ':'')+'show';setTimeout(()=>x.className='',3200)}
async function load(){try{let d=await api('queue');queue=d.patients;surge=d.surge;render()}catch(e){note('API unavailable — run ./run.sh',true)}}
function render(){
 $('#queueCount').textContent=queue.length;$('#surgeToggle').textContent=surge?'Disable surge mode':'Enable 3× surge';$('#surgeToggle').parentElement.classList.toggle('on',surge);
 let urgent=queue.filter(p=>p.score.display_tier<=2).length,review=queue.filter(p=>p.score.flags.includes('Needs clinician review')).length,overdue=queue.filter(p=>p.score.flags.includes('Reassessment overdue')).length;
 $('#metrics').innerHTML=`<div class="metric"><span class="metric-label">IN QUEUE</span><strong>${queue.length}</strong><small>${surge?'3× surge protocol active':'Normal arrival volume'}</small></div><div class="metric"><span class="metric-label">URGENT NOW</span><strong class="up">${urgent}</strong><small>ESI 1–2 recommendations</small></div><div class="metric"><span class="metric-label">NEEDS REVIEW</span><strong>${review}</strong><small>Escalated under uncertainty</small></div><div class="metric"><span class="metric-label">REASSESSMENTS</span><strong>${overdue}</strong><small>${overdue?'Safety window exceeded':'None overdue'}</small></div>`;
 let patients=queue.filter(p=>filter==='all'||filter==='review'&&p.score.flags.includes('Needs clinician review')||color(p.score.display_tier)===filter);
 $('#queueBody').innerHTML=patients.map(p=>{let d=p.data,s=p.score,n=s.display_tier;return `<tr><td><strong>${safe(p.display_name)}</strong><div class="patient-id">${p.id} · ${d.age}y · ${s.age_band}</div></td><td class="signal">${safe(d.complaint)}</td><td class="signal">HR ${d.heart_rate} · RR ${d.respiratory_rate} · SpO₂ ${d.spo2}%<br>${safe(s.reasons[0])}</td><td><span class="tier ${color(n)}"><i class="dot ${color(n)}"></i>${tier(n)}</span>${p.clinician_tier?'<span class="flag">Clinician set tier</span>':s.flags.includes('Needs clinician review')?'<span class="flag">Needs clinician review</span>':''}</td><td class="conf">${s.confidence}%<small>${s.confidence_label} confidence</small></td><td class="wait ${s.flags.includes('Reassessment overdue')?'alert':''}">${p.wait_minutes} min</td><td><button class="row-action" onclick="reviewPatient('${p.id}')">Review</button></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">No matching patients</td></tr>'
}
async function reviewPatient(id){try{let p=await api('patients/'+id),d=p.data,s=p.score,n=p.clinician_tier||s.recommended_tier;$('#modalContent').innerHTML=`<button class="close" onclick="closeModal()">×</button><span class="chip">CLINICIAN REVIEW · ADVISORY ONLY</span><h2>${safe(p.display_name)} <span class="tier ${color(n)}">${tier(n)}</span></h2><p class="subhead">${p.id} · ${d.age} years · ${d.history_available?'Prior record available':'First-time / no history'} · ${s.confidence}% confidence</p><div class="modal-grid"><div class="reason"><strong>Plain-language explanation</strong><br>${safe(s.explanation)}<br><br><strong>Safety controls</strong><br>${safe(s.flags.join(' · ')||'No hard safety rule triggered.')}</div><div class="vitals"><strong>Decision trace</strong><br>Rule safety net: ${tier(s.rule_tier)}<br>ML risk model: ${tier(s.ml_tier)}<br>Fused result: ${tier(s.recommended_tier)}<br>Age band: ${s.age_band}<br><br><strong>Vitals</strong><br>HR ${d.heart_rate} · RR ${d.respiratory_rate}<br>SpO₂ ${d.spo2}% · Temp ${d.temperature}°C<br>SBP ${d.systolic_bp} · AVPU ${d.avpu}</div></div><div class="contrib"><strong>Top ML inputs</strong>${s.feature_contributions.map(x=>`<span>${safe(x.feature)} <b>${x.impact}</b></span>`).join('')}</div><div class="override-block"><strong>Confirm or override recommendation</strong><div class="override-row"><label>Clinician tier<select id="overrideTier">${[1,2,3,4,5].map(x=>`<option value="${x}" ${x===n?'selected':''}>${tier(x)}</option>`).join('')}</select></label><label>Rationale (required)<input id="overrideReason" placeholder="Clinical assessment / reason" /></label><button class="primary" onclick="saveDecision('${id}',${s.recommended_tier})">Record decision</button></div><p class="danger-note">This writes a timestamped, append-only audit record.</p></div>`;$('#patientModal').classList.remove('hidden')}catch(e){note(e.message,true)}}
function closeModal(){$('#patientModal').classList.add('hidden')}
async function saveDecision(id,rec){let tier=+$('#overrideTier').value,reason=$('#overrideReason').value.trim();if(!reason)return note('A rationale is required.',true);try{await api('patients/'+id+'/override',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tier,reason,clinician_id:'NURSE-DEMO-01',clinician_role:'Triage nurse'})});closeModal();await load();note(tier===rec?'Confirmation logged.':'Override recorded in audit trail.')}catch(e){note(e.message,true)}}
async function audit(){try{let rows=await api('audit');$('#auditLog').innerHTML=rows.map(x=>`<article class="audit-entry"><time class="audit-time">${new Date(x.created_at).toLocaleString()}</time><div><strong>${safe(x.event_type.replace('_',' '))}${x.patient_id?' · '+x.patient_id:''}</strong><p>${safe(x.detail.message||`Tier ${x.detail.from_tier||'—'} → ${x.detail.to_tier||'—'}. ${x.detail.reason||''}`)}</p></div><span class="audit-type">${safe(x.event_type)}</span></article>`).join('')}catch(e){note(e.message,true)}}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');let v=b.dataset.view;document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$('#'+v+'View').classList.add('active');$('#viewTitle').textContent=v==='queue'?'Live priority queue':v==='intake'?'New patient intake':'Audit trail';if(v==='audit')audit()});
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});
$('#surgeToggle').onclick=async()=>{try{await api('surge?enabled='+(!surge),{method:'POST'});await load();note(surge?'3× surge policy enabled.':'Standard policy restored.')}catch(e){note(e.message,true)}};
$('#fastForward').onclick=async()=>{try{await api('clock/advance?minutes=30',{method:'POST'});await load();note('30 minutes advanced; queue reassessed.')}catch(e){note(e.message,true)}};
$('#intakeForm').onsubmit=async e=>{e.preventDefault();let f=e.target,d=new FormData(f),g=x=>d.get(x),body={display_name:g('name'),age:+g('age'),heart_rate:+g('hr'),respiratory_rate:+g('rr'),spo2:+g('spo2'),temperature:+g('temp'),systolic_bp:+g('sbp'),avpu:g('avpu'),complaint:g('complaint'),history_available:f.history.checked,active_bleeding:f.bleeding.checked,break_glass:f.breakGlass.checked};try{let p=await api('patients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});f.reset();document.querySelector('[data-view="queue"]').click();await load();reviewPatient(p.id);note('New patient scored and placed in queue.')}catch(e){note(e.message,true)}};
$('#exportAudit').onclick=async()=>{let d=await api('audit'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));a.download='triagesetu-audit-log.json';a.click()};$('#patientModal').onclick=e=>e.target.id==='patientModal'&&closeModal();$('#clock').textContent='LIVE API';load();
