"use client";
import { useMemo, useState } from "react";
import { Download, Search, ScrollText } from "lucide-react";
import type { AuditEntry } from "@/lib/api";
import { apiClient } from "@/lib/api";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
export function AuditTrail({ entries }: { entries: AuditEntry[] }) { const [search, setSearch] = useState(""); const [type, setType] = useState("all"); const types = useMemo(() => ["all", ...Array.from(new Set(entries.map((entry) => entry.eventType)))], [entries]); const filtered = useMemo(() => entries.filter((entry) => (type === "all" || entry.eventType === type) && (!search || `${entry.patientId} ${entry.eventType} ${entry.clinicianId} ${JSON.stringify(entry.detail)}`.toLowerCase().includes(search.toLowerCase()))), [entries, search, type]); const exportLog = async () => { try { const data = await apiClient.exportData(); const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `triagesetu-audit-${Date.now()}.json`; link.click(); URL.revokeObjectURL(url); toast.success("Audit log exported (pseudonymized)."); } catch (error) { toast.error((error as Error).message); } };
  return <section><div className="mb-3 flex flex-col gap-3 sm:flex-row sm:justify-between"><div className="flex flex-wrap gap-1">{types.map((item) => <button key={item} onClick={() => setType(item)} className={cn("rounded-md border px-2.5 py-1.5 text-xs", type === item ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card text-muted-foreground hover:bg-muted")}>{item === "all" ? "All events" : item.replace("_", " ")}</button>)}</div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search audit log" className="h-9 pl-9 text-sm" /></div><Button variant="outline" size="sm" className="h-9 gap-2" onClick={exportLog}><Download className="h-3.5 w-3.5" />Export</Button></div></div><div className="overflow-x-auto rounded-lg border border-border bg-card"><table className="w-full min-w-[720px] text-left text-xs"><thead className="border-b border-border bg-muted text-muted-foreground"><tr><th className="px-4 py-3 font-medium">Timestamp</th><th className="px-4 py-3 font-medium">Event</th><th className="px-4 py-3 font-medium">Patient</th><th className="px-4 py-3 font-medium">Detail</th><th className="px-4 py-3 font-medium">Clinician</th></tr></thead><tbody>{filtered.length ? filtered.slice(0,200).map((entry) => <tr key={entry.id} className="border-b border-border last:border-0"><td className="px-4 py-3 font-mono tabular-nums text-muted-foreground">{new Date(entry.createdAt).toLocaleString("en-IN", { day:"2-digit", month:"short", hour:"2-digit", minute:"2-digit", hour12:false })}</td><td className="px-4 py-3 font-medium">{entry.eventType.replace("_", " ")}</td><td className="px-4 py-3 font-mono tabular-nums">{entry.patientId ?? "—"}</td><td className="max-w-sm truncate px-4 py-3 text-muted-foreground">{entry.detail.message || (entry.detail.from_tier !== undefined ? `Tier ${entry.detail.from_tier} → ${entry.detail.to_tier}. ${entry.detail.reason ?? ""}` : JSON.stringify(entry.detail))}</td><td className="px-4 py-3 text-muted-foreground">{entry.clinicianId ?? "System"}</td></tr>) : <tr><td colSpan={5} className="px-4 py-12 text-center text-muted-foreground"><ScrollText className="mx-auto mb-2 h-5 w-5" />No audit entries match this filter.</td></tr>}</tbody></table></div><p className="mt-3 text-xs text-muted-foreground">Append-only ledger · {filtered.length} of {entries.length} entries shown · exports are pseudonymized.</p></section>; }
