"use client";
import { useAppStore } from "@/lib/store";
import { useTheme } from "next-themes";
import { useEffect, useState, useSyncExternalStore } from "react";
import { Sun, Moon, Clock, Zap, RotateCw, Hospital as HospitalIcon, RefreshCw, ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import type { Hospital } from "@/lib/api";
const TITLES: Record<string, { title: string; subtitle: string }> = { queue: { title: "Live priority queue", subtitle: "Recommendations awaiting clinician confirmation." }, intake: { title: "New patient intake", subtitle: "Record a structured assessment for triage." }, analytics: { title: "Department analytics", subtitle: "Queue and operational indicators." }, beds: { title: "Bed & resource board", subtitle: "Current department capacity." }, staff: { title: "Staff roster", subtitle: "On-duty clinicians and patient load." }, audit: { title: "Clinical audit trail", subtitle: "Append-only record of recommendations and overrides." }, settings: { title: "Workspace settings", subtitle: "Clinical workspace configuration." } };
export function Header({ hospitals, surge, onSurge, onAdvance, onRefresh, refreshing }: { hospitals: Hospital[]; surge: boolean; onSurge: () => void; onAdvance: (minutes: number) => void; onRefresh: () => void; refreshing: boolean }) {
  const { view, hospitalId, setHospitalId, clinicianRole } = useAppStore(); const { theme, setTheme } = useTheme(); const mounted = useSyncExternalStore(() => () => {}, () => true, () => false); const [now, setNow] = useState(new Date()); useEffect(() => { const tick = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(tick); }, []);
  const meta = TITLES[view] ?? TITLES.queue; const active = hospitals.find((h) => h.id === hospitalId) ?? hospitals[0];
  return <header className="sticky top-0 z-20 border-b border-border bg-background"><div className="flex items-start justify-between gap-4 px-4 py-4 sm:px-6 lg:px-8"><div><div className="flex items-center gap-2 text-xs text-muted-foreground"><span className="h-2 w-2 rounded-full bg-triage-green" /> ED live {surge && <span className="ml-1 flex items-center gap-1 text-[color-mix(in_oklch,var(--triage-red)_90%,black)]"><Zap className="h-3 w-3" />Surge</span>}</div><h1 className="mt-2 text-xl">{meta.title}</h1><p className="mt-1 text-sm text-muted-foreground">{meta.subtitle}</p></div><div className="flex flex-wrap justify-end gap-2">
    <DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm" className="h-9 gap-1.5"><HospitalIcon className="h-3.5 w-3.5" /><span className="hidden max-w-36 truncate sm:inline">{active?.name.split(" — ")[0] ?? "Facility"}</span><ChevronDown className="h-3 w-3" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-64"><DropdownMenuLabel>Active facility</DropdownMenuLabel><DropdownMenuSeparator />{hospitals.map((h) => <DropdownMenuItem key={h.id} onClick={() => setHospitalId(h.id)} className="flex flex-col items-start"><span>{h.name}</span><span className="text-xs text-muted-foreground">{h.code} · {h.bedsTotal} beds</span></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>
    <div className="hidden items-center gap-1 border border-border px-2 text-xs text-muted-foreground md:flex"><Clock className="h-3.5 w-3.5" />{mounted && <span className="font-mono">{now.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", hour12: false })}</span>}</div>
    <DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm" className="h-9 gap-1.5"><RotateCw className="h-3.5 w-3.5" /><span className="hidden sm:inline">Reassess</span></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel>Reassess queue</DropdownMenuLabel><DropdownMenuSeparator />{[15,30,60].map((m) => <DropdownMenuItem key={m} onClick={() => onAdvance(m)}>Advance +{m} min</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>
    <Button size="sm" variant={surge ? "destructive" : "outline"} onClick={onSurge} className="h-9 gap-1.5"><Zap className="h-3.5 w-3.5" /><span className="hidden sm:inline">{surge ? "Surge on" : "3× Surge"}</span></Button><Button variant="outline" size="sm" className="h-9 w-9 p-0" onClick={onRefresh} disabled={refreshing}><RefreshCw className={cn("h-3.5 w-3.5", refreshing && "animate-spin")} /></Button><Button variant="outline" size="sm" className="h-9 w-9 p-0" onClick={() => setTheme(theme === "dark" ? "light" : "dark")}>{mounted && theme === "dark" ? <Sun className="h-3.5 w-3.5" /> : <Moon className="h-3.5 w-3.5" />}</Button><span className="hidden items-center border border-border px-2 text-xs text-muted-foreground lg:flex">{clinicianRole}</span>
  </div></div></header>;
}
