"use client";
import { useMemo, useState } from "react";
import { motion } from "framer-motion";
import { Search, AlertTriangle, ChevronRight, Eye, HeartPulse, Wind, Droplet } from "lucide-react";
import type { Patient } from "@/lib/api";
import { TierBadge } from "./tier-badge";
import { ConfidenceMeter } from "./confidence-meter";
import { cn } from "@/lib/utils";
import { Input } from "@/components/ui/input";
type FilterKey = "all" | "red" | "amber" | "green" | "review" | "overdue";
function PatientRow({ p, onReview, index }: { p: Patient; onReview: (p: Patient) => void; index: number }) {
  const tier = p.score.display_tier ?? p.score.recommended_tier; const overdue = p.score.flags.includes("Reassessment overdue"); const review = p.score.flags.includes("Needs clinician review"); const initials = p.displayName.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  return <motion.button layout="position" transition={{ duration: 0.25 }} onClick={() => onReview(p)} className={cn("grid w-full grid-cols-[40px_minmax(140px,1fr)_auto] items-center gap-3 border-b border-border bg-card px-4 py-3 text-left transition-colors hover:bg-muted sm:grid-cols-[44px_minmax(180px,1fr)_100px_120px_110px_100px_auto]", overdue && "border-l-4 border-l-triage-red")}>
    <span className="font-mono text-sm text-muted-foreground">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-full bg-muted text-[10px] font-semibold text-foreground">{initials}</span><span className="truncate text-sm font-semibold">{p.displayName}</span>{p.revealed && <Eye className="h-3 w-3 text-muted-foreground" />}</div><p className="mt-1 truncate pl-9 text-xs text-muted-foreground">{p.id} · {p.data.age}y · {p.data.complaint}</p></div><div className="hidden sm:block"><TierBadge tier={tier} size="sm" /></div><div className="hidden font-mono text-xs tabular-nums sm:flex sm:items-center sm:gap-2"><HeartPulse className="h-3.5 w-3.5 text-muted-foreground" />{p.data.heart_rate}<Wind className="h-3.5 w-3.5 text-muted-foreground" />{p.data.respiratory_rate}<Droplet className="h-3.5 w-3.5 text-muted-foreground" />{p.data.spo2}%</div><div className="hidden sm:block"><ConfidenceMeter value={p.score.confidence} label={p.score.confidence_label} /></div><div className={cn("font-mono text-sm tabular-nums", overdue && "text-[color-mix(in_oklch,var(--triage-red)_90%,black)]")}>{overdue && <AlertTriangle className="mr-1 inline h-3.5 w-3.5" />}{p.waitMinutes}m</div><ChevronRight className="h-4 w-4 text-muted-foreground" />
    <div className="col-span-3 flex items-center justify-between sm:hidden"><TierBadge tier={tier} size="sm" /><span className="font-mono text-xs">HR {p.data.heart_rate} · RR {p.data.respiratory_rate} · SpO₂ {p.data.spo2}%</span>{review && <span className="text-xs text-muted-foreground">Needs review</span>}</div>
  </motion.button>;
}
export function LiveQueue({ patients, onReview }: { patients: Patient[]; onReview: (p: Patient) => void }) {
  const [filter, setFilter] = useState<FilterKey>("all"); const [search, setSearch] = useState("");
  const filtered = useMemo(() => patients.filter((p) => { const tier = p.score.display_tier ?? p.score.recommended_tier; if (search && !`${p.displayName} ${p.id} ${p.data.complaint}`.toLowerCase().includes(search.toLowerCase())) return false; if (filter === "all") return true; if (filter === "review") return p.score.flags.includes("Needs clinician review"); if (filter === "overdue") return p.score.flags.includes("Reassessment overdue"); return (tier <= 2 ? "red" : tier === 3 ? "amber" : "green") === filter; }), [patients, filter, search]);
  const counts = useMemo(() => { const total: Record<FilterKey, number> = { all: patients.length, red: 0, amber: 0, green: 0, review: 0, overdue: 0 }; patients.forEach((p) => { const tier = p.score.display_tier ?? p.score.recommended_tier; total[tier <= 2 ? "red" : tier === 3 ? "amber" : "green"]++; if (p.score.flags.includes("Needs clinician review")) total.review++; if (p.score.flags.includes("Reassessment overdue")) total.overdue++; }); return total; }, [patients]);
  const tabs: { id: FilterKey; label: string }[] = [{id:"all",label:"All"},{id:"red",label:"Urgent"},{id:"amber",label:"Watch"},{id:"green",label:"Stable"},{id:"review",label:"Needs review"},{id:"overdue",label:"Overdue"}];
  return <section><div className="mb-3 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-1">{tabs.map((tab) => <button key={tab.id} onClick={() => setFilter(tab.id)} className={cn("rounded-md border px-2.5 py-1.5 text-xs transition-colors", filter === tab.id ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card text-muted-foreground hover:bg-muted")} >{tab.label} <span className="ml-1 font-mono">{counts[tab.id]}</span></button>)}</div><div className="relative w-full sm:w-72"><Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search patient or complaint" className="h-9 pl-9 text-sm" /></div></div><div className="overflow-hidden rounded-lg border border-border">{filtered.length ? filtered.map((p, i) => <PatientRow key={p.id} p={p} onReview={onReview} index={i} />) : <div className="p-10 text-center text-sm text-muted-foreground">No patients match this view.</div>}</div><p className="mt-3 text-xs leading-5 text-muted-foreground">Recommendations assist licensed clinicians; they do not make clinical decisions. Rules can only escalate, never downgrade.</p></section>;
}
