"use client";

import { useEffect, useState } from "react";
import { Activity, Brain, CheckCircle2, Droplet, FileText, HeartPulse, Send, Thermometer, Wind } from "lucide-react";
import type { Note, Patient } from "@/lib/api";
import { apiClient } from "@/lib/api";
import { TierBadge } from "./tier-badge";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { useAppStore } from "@/lib/store";
import { toast } from "sonner";
import { TIER_LABELS } from "@/lib/triage";

export function PatientDetail({ patient, open, onClose, onUpdated }: { patient: Patient | null; open: boolean; onClose: () => void; onUpdated: () => void }) {
  const { clinicianId, clinicianRole } = useAppStore();
  const [tier, setTier] = useState(5); const [reason, setReason] = useState(""); const [notes, setNotes] = useState<Note[]>([]); const [noteText, setNoteText] = useState(""); const [saving, setSaving] = useState(false);
  // The dialog is reused between patients; reset its draft state whenever a new record opens.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (patient) { setTier(patient.clinicianTier ?? patient.score.recommended_tier); setReason(""); setNotes(patient.notes ?? []); setNoteText(""); } }, [patient]);
  if (!patient) return null;
  const { data, score } = patient; const displayTier = patient.clinicianTier ?? score.recommended_tier;
  const save = async () => { if (reason.trim().length < 3) return toast.error("Add a short clinical rationale before recording."); setSaving(true); try { await apiClient.override(patient.id, { tier, reason, clinician_id: clinicianId, clinician_role: clinicianRole }); toast.success(tier === score.recommended_tier ? "Recommendation confirmed and logged." : "Clinical override recorded and logged."); onUpdated(); onClose(); } catch (error) { toast.error((error as Error).message); } finally { setSaving(false); } };
  const updateStatus = async (status: "treated" | "transferred") => { try { await apiClient.setStatus(patient.id, status, clinicianId, clinicianRole); toast.success(status === "treated" ? "Patient discharged from queue." : "Patient marked for transfer."); onUpdated(); onClose(); } catch (error) { toast.error((error as Error).message); } };
  const addNote = async () => { if (!noteText.trim()) return; try { const note = await apiClient.addNote(patient.id, { author: clinicianId, role: clinicianRole, text: noteText.trim() }); setNotes((current) => [note, ...current]); setNoteText(""); toast.success("Clinical note added."); } catch (error) { toast.error((error as Error).message); } };
  return <Dialog open={open} onOpenChange={(next) => !next && onClose()}><DialogContent className="fixed left-1/2 top-1/2 z-50 flex max-h-[90vh] w-[96vw] max-w-[900px] -translate-x-1/2 -translate-y-1/2 flex-col gap-0 overflow-hidden rounded-lg border bg-card p-0">
    <DialogHeader className="shrink-0 border-b border-border px-5 py-4"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2"><DialogTitle className="truncate text-lg">{patient.displayName}</DialogTitle><TierBadge tier={displayTier} size="sm" /></div><DialogDescription className="mt-1 font-mono text-xs tabular-nums">{patient.id} · {data.age}y · {score.age_band} · waiting {patient.waitMinutes} min</DialogDescription></div><div className="text-right text-xs text-muted-foreground"><div>{score.confidence_label}</div><div className="mt-1 font-mono tabular-nums text-foreground">{score.confidence}% confidence</div></div></div></DialogHeader>
    <div className="flex-1 overflow-y-auto px-5 py-4"><section aria-label="Vital signs" className="grid grid-cols-3 gap-2 sm:grid-cols-6"><Vital icon={HeartPulse} label="HR" value={data.heart_rate} unit="bpm" /><Vital icon={Wind} label="RR" value={data.respiratory_rate} unit="/min" /><Vital icon={Droplet} label="SpO₂" value={data.spo2} unit="%" /><Vital icon={Thermometer} label="Temp" value={data.temperature} unit="°C" /><Vital icon={Activity} label="BP" value={data.systolic_bp} unit="mmHg" /><Vital icon={Brain} label="AVPU" value={data.avpu} unit="" /></section>
      <div className="mt-4 grid gap-4 md:grid-cols-[1.15fr_.85fr]"><section className="space-y-4"><div><h2 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Clinical summary</h2><p className="mt-2 text-sm leading-6">{score.explanation}</p>{score.flags.length > 0 && <div className="mt-3 flex flex-wrap gap-1.5">{score.flags.map((flag) => <span key={flag} className="rounded-md border border-border bg-muted px-2 py-1 text-xs">{flag}</span>)}</div>}</div><div className="border-t border-border pt-4"><h2 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Chief complaint</h2><p className="mt-2 text-sm">{data.complaint}</p><p className="mt-2 text-xs text-muted-foreground">{data.history_available ? "History available" : "No history available"}{data.active_bleeding ? " · Active bleeding" : ""}</p></div></section>
        <section className="rounded-lg border border-border bg-muted/30 p-4"><h2 className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground"><FileText className="h-3.5 w-3.5" />Recommendation trace</h2><div className="mt-4 space-y-3"><Trace label="Rule safety net" tier={score.rule_tier} /><Trace label="ML risk model" tier={score.ml_tier} /><Separator /><Trace label="System recommendation" tier={score.recommended_tier} strong />{patient.clinicianTier !== null && <Trace label="Current clinician tier" tier={patient.clinicianTier} strong />}</div>{score.feature_contributions.length > 0 && <><Separator className="my-4" /><h3 className="text-xs font-medium text-muted-foreground">Primary inputs</h3><div className="mt-2 space-y-2">{score.feature_contributions.slice(0, 4).map((item) => <div key={item.feature} className="flex items-center justify-between text-xs"><span className="text-muted-foreground">{item.feature}</span><span className="font-mono tabular-nums">{item.impact}</span></div>)}</div></>}</section></div>
      <section className="mt-5 border-t border-border pt-4"><div className="flex items-center justify-between"><h2 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Clinical notes</h2><span className="text-xs text-muted-foreground">{notes.length} recorded</span></div>{notes.length > 0 && <div className="mt-3 max-h-28 space-y-2 overflow-y-auto">{notes.map((note) => <div key={note.id} className="border-l-2 border-primary pl-3 text-sm"><p>{note.text}</p><p className="mt-1 text-xs text-muted-foreground">{note.author} · {new Date(note.createdAt).toLocaleString("en-IN", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", hour12: false })}</p></div>)}</div>}<div className="mt-3 flex gap-2"><Textarea value={noteText} onChange={(event) => setNoteText(event.target.value)} placeholder="Add a clinical note" rows={1} className="min-h-9 text-sm" /><Button size="sm" className="h-9 shrink-0" onClick={addNote} disabled={!noteText.trim()}><Send className="h-3.5 w-3.5" /></Button></div></section>
    </div>
    <footer className="shrink-0 border-t border-border bg-card px-5 py-4"><div className="grid gap-3 sm:grid-cols-[150px_1fr_auto]"><div><label className="text-xs font-medium text-muted-foreground">Clinical tier</label><Select value={String(tier)} onValueChange={(value) => setTier(Number(value))}><SelectTrigger className="mt-1 h-9 w-full text-sm"><SelectValue /></SelectTrigger><SelectContent>{[1,2,3,4,5].map((value) => <SelectItem key={value} value={String(value)}>{TIER_LABELS[value]}</SelectItem>)}</SelectContent></Select></div><div><label className="text-xs font-medium text-muted-foreground">Rationale</label><Textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Reason for confirmation or override" rows={1} className="mt-1 min-h-9 resize-none text-sm" /></div><div className="flex items-end gap-2"><Button variant="outline" size="sm" className="h-9" onClick={() => updateStatus("transferred")}>Transfer</Button><Button size="sm" className="h-9 gap-2" disabled={saving || reason.trim().length < 3} onClick={save}><CheckCircle2 className="h-3.5 w-3.5" />{saving ? "Saving" : "Record"}</Button></div></div><button type="button" onClick={() => updateStatus("treated")} className="mt-3 text-xs text-muted-foreground underline underline-offset-4 hover:text-foreground">Mark treated and remove from queue</button></footer>
  </DialogContent></Dialog>;
}
function Vital({ icon: Icon, label, value, unit }: { icon: typeof HeartPulse; label: string; value: string | number; unit: string }) { return <div className="rounded-md border border-border bg-card p-2"><div className="flex items-center gap-1 text-[10px] uppercase text-muted-foreground"><Icon className="h-3 w-3" />{label}</div><div className="mt-1 font-mono text-sm font-semibold tabular-nums">{value}<span className="ml-0.5 text-[10px] font-normal text-muted-foreground">{unit}</span></div></div>; }
function Trace({ label, tier, strong = false }: { label: string; tier: number; strong?: boolean }) { return <div className={strong ? "flex items-center justify-between rounded-md bg-card px-2 py-2" : "flex items-center justify-between"}><span className={strong ? "text-xs font-medium" : "text-xs text-muted-foreground"}>{label}</span><TierBadge tier={tier} size="sm" /></div>; }
